### ISSUE TITLE
Additional exif information

### ISSUE THREAD

**Issue by Natenom** [wavexx/fgallery#17]
Could you please add some exif information related to photography like aperture, focal length, exposure, ISO value within an optional infobox? I think it is better for interested photographers to be able to see those values.
With this fgallery would be perfect for me.

**Comment by wavexx** [comment]
So now that captions are in, I was thinking of also adding exif metadata.
Is anyone willing to help for icons?

I think that all icons, except maybe the "download" one need work.
Even the icon I added for captions is badly scaled, but I didn't have time to do some grid fitting.

**Comment by Natenom** [comment]
I asked someone for some ideas ... will report here :)

**Comment by wavexx** [comment]
On 14/01/16 17:41, Natenom wrote:
> I asked someone for some ideas ... will report here :)

The major constraint is really that icons should be compatible with GPL2+.

I've tried some gnome symbolic icons, but they arguably need some work
to scale decently at 24x24. I've seen many other "iconic" icons around
in the last year, but really I didn't have much time to fiddle with it.

For example, I really think the "eye" icon stinks (too wide/full), but
well... just some attempts with inkscape.

We also need an icon for the "exif" toggle (for both the show/hide states).

**Comment by wavexx** [comment]
I'm planning for either a 1.8.1 bugfix release, or roll these into 1.9 with the extra exif data.
Any news on the icons? ;)
