### ISSUE TITLE
Different sizes for different display size

### ISSUE THREAD

**Issue by tomasgreif** [wavexx/fgallery#21]
Would it make se se to generate more versions od blurs thumbs and photos for different displays? It is OK to have 1200x1600 image when using bigger screen, but looks like too big (both size and dimensions) when viewing gallery on mobile phone. This could further improve load time.

**Comment by wavexx** [comment]
Thinking aloud, we could use imagesets in the viewer nowdays, but we'd still need to generate multiple versions of the image in fgallery. Not that hard, but quite wasteful in terms of space.
