### ISSUE TITLE
Improper "identify" / "convert" detect failure

### ISSUE THREAD

**Issue by jmcaine** [wavexx/fgallery#25]
On one of my systems, the 
```if(system("identify >/dev/null 2>&1") || system("convert >/dev/null 2>&1")) {```
check fails because the calls return "256".  However, identify and convert both work just fine.  On my other systems, this doesn't happen.  The Imagemagick on this system is 6.8.9-9.  I'd do a pull-request, but not sure exactly how you'd like to resolve this.  For a test, when I comment the entire check out, everything works wonderfully.

**Comment by wavexx** [comment]
fgallery 1.7 fixed this issue already. Which version are you using?

**Comment by jmcaine** [comment]
Oops.  I'm very sorry, I see I was not up to date.

**Comment by wavexx** [comment]
Assuming it works.. I'm closing ;)
