### ISSUE TITLE
plain, solid color background

### ISSUE THREAD

**Issue by krupan** [wavexx/fgallery#27]
Is it possible to have a simple solid color background behind the images?

**Comment by wavexx** [comment]
On 06/08/2015 01:24 AM, krupan wrote:
> Is it possible to have a simple solid color background behind the images?

I need to add an option for this.

Currently, if you remove the gallery/blurs directory it will show a flat
black.

**Comment by krupan** [comment]
That works.  Thanks!

**Comment by wavexx** [comment]
Let me argument this... I was discussing with a colleague a couple of weeks ago about having a flat color background (black, basically). It seems that whenever the main image is almost an uniform gray, then a flat black is generally more appealing.

I was trying to see if there's some logic I can use to automatically remove unpleasant blurs and replace it with a solid color instead.

Do you have any practical reason to disable the background, or is it just aesthetics? If so, can you provide some examples as when do you think a solid color would be nicer?

**Comment by krupan** [comment]
For some reason I just found the blur background distracting. For me
personally I don't want it for any picture. I'm sure my sense of aesthetics
shouldn't be generalized for everyone. I'm a computer geek, after all :-)

Bryan

**Comment by wavexx** [comment]
On 06/29/2015 12:24 AM, krupan wrote:
> For some reason I just found the blur background distracting. For me
> personally I don't want it for any picture. I'm sure my sense of aesthetics
> shouldn't be generalized for everyone. I'm a computer geek, after all :-)

What about borders then..? ;)

**Comment by krupan** [comment]
On Mon, Jun 29, 2015 at 2:25 AM, wavexx <notifications@github.com> wrote:

> On 06/29/2015 12:24 AM, krupan wrote:
> > For some reason I just found the blur background distracting. For me
> > personally I don't want it for any picture. I'm sure my sense of
> aesthetics
> > shouldn't be generalized for everyone. I'm a computer geek, after all :-)
>
> What about borders then..? ;)


Heh.  I think solid color borders are fine, but I'd have to see it to be
sure.  Again, not any kind of artist or graphic designer here.

Bryan
