### ISSUE TITLE
Hidden Files on SMB share, uploaded by Mac creating unprocessable dot underscore files

### ISSUE THREAD

**Issue by markgweber** [wavexx/fgallery#28]
I realize this is highly specific, but here is my situation.  I have an smb share on a linux host at /media/photos/.  For arguments sake, let's say I create a folder called 'Airshow'.  Using my Mac I upload a bunch of pictures to 'Airshow'  (/media/photos/Airshow). When I would run my fgallery command:

#sudo fgallery --min-thumb 112x150 --max-thumb 200x267 /media/photos//Airshow ./Airshow

I was getting all sorts of weird errors like:
```
Use of uninitialized value $props{"FileType"} in string eq at /usr/local/bin/fgallery line 479.
Use of uninitialized value $props{"FileType"} in string eq at /usr/local/bin/fgallery line 488.
+ touch -r /media/photos/Airshow/._IMG_4628.jpg ./Airshow/files/__IMG_4628.jpg
+ convert ./Airshow/files/__IMG_4628.jpg.tmp -gamma 0.454545 -geometry 1600x1200> -print %w\n%h -gamma 2.2 +profile !icc,* -quality 90 ./Airshow/imgs/__IMG_4628.jpg
convert.im6: no decode delegate for this image format `./Airshow/files/__IMG_4628.jpg.tmp' @ error/constitute.c/ReadImage/544.
convert.im6: no images defined `./Airshow/imgs/__IMG_4628.jpg' @ error/convert.c/ConvertImageCommand/3044.
error: command "convert ./Airshow/files/__IMG_4628.jpg.tmp -gamma 0.454545 -geometry 1600x1200> -print %w\n%h -gamma 2.2 +profile !icc,* -quality 90 ./Airshow/imgs/__IMG_4628.jpg" failed
 ```

Turns out that when a mac uploads a file to an smb share, it leaves a nice pile of hidden files containing stuff to aid previews.  For instance:
```
-rwxr--r--  1 nobody nogroup    4096 Jun 13 01:05 ._IMG_4628.jpg
-rwxr--r--  1 nobody nogroup 3918593 Jun 13 01:03 IMG_4628.jpg
```
 So for every IMG_xxxx.jpg file I had, I also had a ._IMG_xxxx.jpg that was throwing fgallery for a loop because those aren't really images to be processed.  The fix for me was to apply this patch:
```
--- /home/media/fgallery-master/fgallery	2014-09-18 10:48:13.000000000 -0500
+++ /usr/local/bin/fgallery	2015-06-15 00:53:10.500684675 -0500
@@ -346,7 +346,8 @@
   {
     my $file = $_;
     return if(!-f $file);
-    my (undef, undef, $suffix) = fileparse($file, qr/\.[^.]*$/);
+    my ($name, undef, $suffix) = fileparse($file, qr/\.[^.]*$/);
+    return if ($name =~ /^\./); # Skip hidden files
     return if(length($suffix) < 2);
     $suffix = lc(substr($suffix, 1));
     if(any { $_ eq $suffix } @exts) {
```

This skips hidden files and skirts my problem entirely.  I'm not sure if that's something fgallery wants to incorporate from an architectural standpoint (skipping all dot files), but maybe a flag could be added like --skip-hidden-files so folks who are sourcing their photos from a Linux SMB share where the photos were uploaded by a mac will keep fgallery from dying.

**Comment by wavexx** [comment]
On 06/15/2015 07:56 AM, markgweber wrote:
> Turns out that when a mac uploads a file to an smb share, it leaves a nice pile of hidden files containing stuff to aid previews.  For instance:

Aah, good old finder stuff. I was running OSX until Tiger, so I do know
the problem.

Could you just send me an image+._IMG file so that I can build a test
case for it?

I'd like to see what ExifTool gets out of it, maybe I can skip based on
something else than the filename.

But skipping hidden files sounds reasonable to me as well.
You might not want fgallery to crawl and discover hidden stuff...

**Comment by wavexx** [comment]
I was able to get one of those from a colleague. I fixed this twice in the code, by ignoring hidden files and ignoring empty results of ExifTool (for example, for broken files).

**Comment by wavexx** [comment]
Let me know if this fixes it for you, and close the issue if done.

**Comment by markgweber** [comment]
Works great, thanks!
