### ISSUE TITLE
Issues on OSX Mavericks 10.10.3

### ISSUE THREAD

**Issue by sleyb** [wavexx/fgallery#30]
Hi,

I am trying to run the app on Mavericks after running your suggested steps on the ReadMe and am still running into errors.

Can't locate Image/ExifTool.pm in @INC (@INC contains: /opt/local/lib/perl5/site_perl/5.16.3/darwin-thread-multi-2level /opt/local/lib/perl5/site_perl/5.16.3 /opt/local/lib/perl5/vendor_perl/5.16.3/darwin-thread-multi-2level /opt/local/lib/perl5/vendor_perl/5.16.3 /opt/local/lib/perl5/5.16.3/darwin-thread-multi-2level /opt/local/lib/perl5/5.16.3 /opt/local/lib/perl5/site_perl /opt/local/lib/perl5/vendor_perl .) at ./fgallery line 26.
BEGIN failed--compilation aborted at ./fgallery line 26.

What am I missing?

Thanks,
Steven

**Comment by wavexx** [comment]
[How] did you install ExifTool? Using ``sudo cpan`` as recommended or through other means?

**Comment by sleyb** [comment]
I used the Mac instructions which are:

sudo port install imagemagick lcms2 jpeg jpegoptim pngcrush
sudo cpan -i JSON JSON::XS Image::ExifTool

I also installed ExifTool using the DMG installer from the main website.

**Comment by wavexx** [comment]
Could you maybe post the output of running

````
sudo cpan -i Image::ExifTool
````

and also
````
perl -V
````

Thanks.

**Comment by wavexx** [comment]
I now discovered exiftool has been updated also avilable through macports.
Maybe:

````
sudo port install p5-image-exiftool
````

installs it correctly now.

**Comment by wavexx** [comment]
Any success with the updated instructions?

**Comment by wavexx** [comment]
Closing this, as recent fgallery versions are reported to work.
Please re-open if you need assistance.
