### ISSUE TITLE
performance: Don't download every thumbnail when the gallery opens

### ISSUE THREAD

**Issue by Baughn** [wavexx/fgallery#35]
Displaying every single thumbnail on the roller is bad for performance, for several reasons. From most to least bad:

- Downloading them all takes time. Parsing them all takes more time. Even if they're cached, it can lead to a gallery taking several seconds to initialize even for relatively modest image counts. Example: https://madoka.brage.info/baughn/oso/
- For a large gallery the complete thumbnail set can be several megabytes. This is bad for users on metered connections.
- For non-HTTP2 servers, serving large numbers of small files means making more roundtrips, due to the pipelining limit. This problem will go away with time.
- Browsers aren't good with huge numbers of DOM elements. This won't matter unless there are thousands at least. (I wouldn't suggest trying to handle this just yet, as redoing the layout costs *even more*.)

I'd recommend loading only the thumbnails that are visible on the roller, plus a viewport-sized buffer on either side.

**Comment by wavexx** [comment]
On 01/01/16 16:34, Svein Ove Aas wrote:
>   * Browsers aren't good with huge numbers of DOM elements. This won't
>     matter unless there are thousands at least. (I wouldn't suggest
>     trying to handle this just yet, as redoing the layout costs /even
>     more/.)
> 
> I'd recommend loading only the thumbnails that are visible on the
> roller, plus a viewport-sized buffer on either side.

Yes, that's something I was thinking about as a short-term measure.
But the point you make about the number of DOM elements is also a very
good one.

Setting a delayed load using the visibility event is easy, but it won't
solve the huge number of thumbnails elements. Performing dynamic
creation in the pane though would imply doing all layout via JS as well.

**Comment by Baughn** [comment]
How about creating all the elements, but leaving the img 'src' attribute unset?

Low-hanging fruit first.

**Comment by wavexx** [comment]
Give it a try. I now load thumbnails on demand, with a prebuffering of half a page.

**Comment by wavexx** [comment]
There are still some glitches on this..

**Comment by wavexx** [comment]
Hopefully fixed for good. Please test if you like the behavior.

**Comment by Baughn** [comment]
Seems good to me. Galleries open much faster now.

**Comment by wavexx** [comment]
On 03/01/16 13:22, Svein Ove Aas wrote:
> Seems good to me. Galleries open much faster now.

Out of curiosity, what's the largest gallery you have?
[can I see it?]

**Comment by Baughn** [comment]
At present? It's https://madoka.brage.info/baughn/x, which is just a completely random set of pictures I've linked from various places on the internet over the years. I haven't updated the gallery, though.
