### ISSUE TITLE
fgallery GUI

### ISSUE THREAD

**Issue by wavexx** [wavexx/fgallery#38]
If anybody is interested, I had a first go at designing a simple GUI for fgallery for those that prefer something graphical. Unfortunately, I didn't have much time to polish it, so here it is:

[fgallery.ui.zip](https://github.com/wavexx/fgallery/files/101883/fgallery.ui.zip)

If anybody wants to help, it's written using the "Qt4 Designer", so there's no need for previous programming experience (it's a drag&drop UI designer similar to glade).

If the GUI is in good shape, I'll write the actual code myself.

**Comment by rmaddox** [comment]
The point of fgallery is that it is quick and command line. It is quite easy to implement its GUI. I use for some command line applications this package: http://kaptain.sourceforge.net/ and it is fairly simple to implement a kaptain script for fgallery.

Another possibility would be with some widgets like zenity, or with simple shell script running some of those widgets already available on the system

**Comment by wavexx** [comment]
Thanks for mentioning kaptain, never head of it before. That being said, writing a qt4 UI for a front-end is not much harder (look at how fcaption works). Try to open the attached UI (in the first message) with "designer" if you want to have a look.

It's also not intended as a substitute to the command line. I just don't want to ship with a half-baked UI, so it's here if someone wants a starting point.

**Comment by rmaddox** [comment]
fcaption link?

**Comment by wavexx** [comment]
On 30/01/16 13:23, Rosario Maddox wrote:
> fcaption link?

It's in the source (utils/fcaption).

See:

http://www.thregr.org/~wavexx/software/fgallery/#image-captioning

**Comment by rmaddox** [comment]
This looks good. Only I am not sure how many people will use the UI, as this is clearly command line. UI is like one step back.

![fgalleri-ui](http://rcdrun.com/images/upload/tmp/2016-01-30-13:25:46.jpg)

**Comment by wavexx** [comment]
For generating the gallery I personally don't. I almost exclusively use a command line myself.
But for editing image data, I do want to see the image at the same time.
