### ISSUE TITLE
Use of uninitialized value in multiplication and similar

### ISSUE THREAD

**Issue by rmaddox** [wavexx/fgallery#39]
Used this command line:
```
fgallery -s -c txt -d --index http://www.duckduckgo.com . gallery
```
and I had all .txt ready.
got this
```
Use of uninitialized value $id in string eq at /something/fgallery line 94
```
and later this 
```
Use of uninitialized value in multiplication (*) at /home/data1/protected/Programming/git/fgallery/fgallery line 580
Use of uninitialized value $root in concatenation (.) or string at /home/data1/protected/Programming/git/fgallery/fgallery line 594
```

I guess this happened because of using . as directory of pictures.

**Comment by wavexx** [comment]
On 30/01/16 13:54, Rosario Maddox wrote:
> Used this command line:
> 
> |fgallery -s -c txt -d --index http://wwwduckduckgocom gallery |
> 
> and I had all txt ready
> got this
> 
> |Use of uninitialized value $id in string eq at /something/fgallery line 94 |
> 
> and later this
> 
> |Use of uninitialized value in multiplication (*) at
> /home/data1/protected/Programming/git/fgallery/fgallery line 580 Use of
> uninitialized value $root in concatenation () or string at
> /home/data1/protected/Programming/git/fgallery/fgallery line 594 |
> 
> I guess this happened because of using as directory of pictures

There is probably a single file which is causing trouble.
Can you post (even privately) the entire output of

  fgallery -v ... > log 2>&1 ?

**Comment by wavexx** [comment]
Fixed in the last commits.
