### ISSUE TITLE
Remove navigation arrows

### ISSUE THREAD

**Issue by wavexx** [wavexx/fgallery#40]
I no longer remember when I actually used the navigation arrows (back/forward arrows around the main image).

I noticed most people click on the thumbnail instead, and the auto-centering (plus the various shortcuts) makes going through the gallery just as fast with less clutter on top of the image.

Anybody wants to keep the arrows?

**Comment by paolobenve** [comment]
yes, they must be kept

**Comment by wavexx** [comment]
On Sun, Apr 02 2017, Paolo wrote:
> yes, they must be kept

would you elaborate?
