### ISSUE TITLE
enhancement: let the user set the minupscale var during static generation

### ISSUE THREAD

**Issue by seb-ksl** [wavexx/fgallery#43]
When using "low" resolution (e. g. 800x600 and 600x800) images for album generation, the images appear stretched and blurry in the album on a screen set bigger than image resolution (e. g. 1680x1050).
I found that actually this behaviour is intended by the use of the minupscale variable in the index.js file of the generated album. This variable is set by default to 640x480. If I understood correctly, this means that every image bigger than this resolution will be stretched to fit screen resolution, leading to ugly blurry results. I set it by hand to 10000x10000 and my 800x600 images are now displayed centered and untouched.

Hence my input: do you agree to add an argument to the fgallery command that would let the user set this variable? I suppose something like `fgallery --max-full 800x800 --minupscale 801x801 pics album "Album Title"` would make sense.

Regards

**Comment by wavexx** [comment]
On Tue, Mar 08 2016, seb-ksl <notifications@github.com> wrote:
> Hence my input: do you agree to add an argument to the fgallery command that
> would let the user set this variable? I suppose something like fgallery -
> -max-full 800x800 --minupscale 801x801 pics album "Album Title" would make
> sense.

minupscale is a bit of a hack. It's mostly intended for icons and such
images, where over-stretching will result in something which is not just
"blurry", but plainly unwatchable.

I'd be cautious about setting minupscale just to avoid blurryness. The
issue is that if you have a high-resolution monitor (200+ dpi), you're
actually preventing people to see small images. They'll look like a
thumbnail without stretching.

It's already an issue for small images, since in this case minupscale
will prevent small images to be seen at all.

We *could* detect, instead, whether the image is within a 0.1x
magnification (up or down) in respect of the final image size. If it's
within this boundary, meaning you're close to the target size anyway,
avoid scaling to preserve sharpness.

What's your screen resolution in your case?

**Comment by seb-ksl** [comment]
OK I see your point. Doing things properly seems like a better idea indeed.

My use case:
- Images resized to have their biggest dimension == 1024 (because of a self-hosted server behind a not-so-high-speed connection)
- Screen resolution: 1680x1050

Results:
- With minupscale set to default, landscape images are really stretched and blurry. Portrait images are fine.
- With minupscale increased to 10000x10000, all images are un-stretched and display fine at their native resolution.

**Comment by wavexx** [comment]
Could you give an example size for an image that would be stretched too much? 1024x640?

**Comment by seb-ksl** [comment]
For example, this 1000x667 image with default index.js settings:
![stretched](https://cloud.githubusercontent.com/assets/4478345/13639881/0670814a-e613-11e5-8ebd-2cf9e8a35b3e.png)

And modified index.js (minupscale set to 10000x10000):
![unstretched](https://cloud.githubusercontent.com/assets/4478345/13639858/f472cbd8-e612-11e5-9b4c-c300b72a91b0.png)

**Comment by wavexx** [comment]
Hmm, this is a bit far beyond what I had in mind (this is a ~30% stretch already).
Too far from a perfect ratio.

**Comment by seb-ksl** [comment]
So setting the max stretch to 10% as you proposed might actually be the best way to go, right?

**Comment by wavexx** [comment]
On Wed, Mar 09 2016, seb-ksl <notifications@github.com> wrote:
> So setting the max stretch to 10% as you proposed might actually be
> the best way to go, right?

I was thinking of doing the opposite, stretch only if the difference is
larger than 10%. And in this case, it is.

**Comment by seb-ksl** [comment]
But I'm confused. Let's take the corner case of a 641x481 image displayed on a 4096x2160 screen. With current settings, it would appear stretched as hell, right?

I know you intended fgallery to share high-res images, but in the case of self-hosting it is often impossible to server out-of-the-camera pictures in reasonable times, hence the use of smaller pictures.

**Comment by wavexx** [comment]
On Wed, Mar 09 2016, seb-ksl <notifications@github.com> wrote:
> But I'm confused. Let's take the corner case of a 641x481 image
> displayed on a 4096x2160 screen. With current settings, it would
> appear stretched as hell, right?

Yes, however that's also what you want at 4k.

The scale on the screen is independent of the actual resolution of the
image. It's like having a blurry scan of an old photo. There's not much
you can do, but you still want to see it just as big.

What I was talking about was to snap scaling at perfect fractions, so
that you trade off some space of the screen with less stretching
artifacts.

That that this mostly affects scales which are close to 0.9<x<1.1, where
you have a lot of aliasing and not enough pixels to play with. It makes
sense here.

But like I said, 1.3 is a bit large for this. I have plenty of images
that I took with old cameras that are "small" by today's resolutions,
but on a phone or a hi-res screen putting them full-screen is the only
choice you have.

**Comment by seb-ksl** [comment]
OK I totally see your point now :-)

However I'm glad I found the minupscale variable that allows me to adjust this behaviour, because the default stretching might not meet everyone's need. It simply requires that the user knows where to look to change the setting, so I was only asking about making it more "accessible".

Anyway, thanks for taking time to answer my naive remarks, and thanks for sharing this really nice work ;-)

**Comment by wavexx** [comment]
On Thu, Mar 10 2016, seb-ksl <notifications@github.com> wrote:
> Anyway, thanks for taking time to answer my naive remarks, and thanks
> for sharing this really nice work ;-)

I do see your point though. I'm just trying to think of some rule that
wouldn't need tweaking and/or break viewing.

I seem to remember that there's now a method to query the physical size
of the screen in addition to the resolution.
