### ISSUE TITLE
arch linux package

### ISSUE THREAD

**Issue by tjaartvdwalt** [wavexx/fgallery#49]
Hi thanks for a great project,

With input from @zorun I have packaged fgallery for Arch Linux. It is available in the Arch User Repositories: https://aur.archlinux.org/packages/fgallery/

If you think its worth it you could add that to the installation documentation.

**Comment by wavexx** [comment]
I added a new section in the README.
What do you think?

**Comment by tjaartvdwalt** [comment]
great thanks!
