### ISSUE TITLE
Issue in Mac OSX Yosemite

### ISSUE THREAD

**Issue by BurnNG** [wavexx/fgallery#50]
Hi

I get the following error when running ./fgallery:

> cp: the -H, -L, and -P options may not be specified with the -r option.

Thanks!

**Comment by haennima** [comment]
Hello

Please use the latest version of fgallery. This problem has been fixed.

**Comment by haennima** [comment]
cp -R instead of cp -r

**Comment by wavexx** [comment]
Fixed in 1.8.2
