### ISSUE TITLE
Invalid SOS parameters for sequential JPEG

### ISSUE THREAD

**Issue by pcav** [wavexx/fgallery#53]
While creating a gallery, I get a lot of these errors. It seems an old error in a lib, now solved:
https://github.com/golang/go/issues/3916

**Comment by wavexx** [comment]
On Sun, Jul 24 2016, Paolo Cavallini <notifications@github.com> wrote:
> While creating a gallery, I get a lot of these errors. It seems an old
> error in a lib, now solved:
> https://github.com/golang/go/issues/3916

This fix mentions an issue in the go image writer though?

Running convert with -quiet seems to suppress it, but since this is the
only warning I saw so far, I'm a bit cautious.

Are your images produced directly by a camera or by some software?

**Comment by pcav** [comment]
Directly by the camera.
Thanks!

**Comment by pcav** [comment]
I guess it has something to do with base libs, since the error is thrown also for pictures from my usual phone.
I'm on Debian Sid, so things change rapidly. Most probably it has nothing to do with fgallery, feel free to close it.
Sorry about the noise.

**Comment by pcav** [comment]
Further explored the issue: it happens only for a few specific photos (13 over a gallery of >500). I can attach one here if of interest.

**Comment by wavexx** [comment]
I now run all convert invocations with -quiet, which suppresses the warnings. Can you check?

**Comment by pcav** [comment]
I'd love to test it, but cloning the repo and

`./fgallery /photo/ /sail/album_kos`

throws a segfault. I can happily do it when a deb is available on sid.

**Comment by wavexx** [comment]
On Tue, Oct 25 2016, Paolo Cavallini <notifications@github.com> wrote:
> I'd love to test it, but cloning the repo and
>
> ./fgallery /photo/ /sail/album_kos
>
> throws a segfault. I can happily do it when a deb is available on sid.

I'm on sid too. I'd love to know why it segfaults on your system.

**Comment by pcav** [comment]
Not quite sure how to proceed. I tested:
```
./fgallery --version
fgallery 1.8.2
```
but
```
./fgallery /home/paolo/Immagini/2016/kos/photo/ /home/paolo/public_html/sail/album_kos
Errore di segmentazione
```

**Comment by wavexx** [comment]
I've found this to be a bug in older perl versions. I'll see what I can do to work around it.

**Comment by wavexx** [comment]
Hopefully fixed in the current master. Can you refresh and try again?

**Comment by pcav** [comment]
Confirmed, it works now. Thanks a lot.
