### ISSUE TITLE
Internationalization for captions

### ISSUE THREAD

**Issue by tjaartvdwalt** [wavexx/fgallery#61]
Thanks for a great project!

This is a feature request, but I would be willing to help with development if you are positive about the idea.

My use case: I am South African, and currently live in the USA. My family back home likes to see the captions in Afrikaans, but my friends in the US need English.

I do not know all the implications this will have, but I envision you would have an extra button in the album to switch languages. You also would need to improve the `fcaption` utility to allow for multilingual caption entry.

Please let me know your thoughts.

**Comment by wavexx** [comment]
On Wed, Aug 31 2016, Tjaart van der Walt <notifications@github.com> wrote:
> My use case: I am South African, and currently live in the USA. My family back home likes to see the captions in Afrikaans, but my friends in the US need English.
>
> I do not know all the implications this will have, but I envision you would have an extra button in the album to switch languages. You also would need to improve the `fcaption` utility to allow for multilingual caption entry.

It's mostly an issue on where the data is stored, and how.
I don't think that EXIF directly support localization, and the same is
probably true for XMP.

How would you store localized messages in the text variant?

**Comment by tjaartvdwalt** [comment]
> I don't think that EXIF directly support localization, and the same is probably true for XMP.

I did not even consider those cases, since I use the txt files option.

> How would you store localized messages in the text variant?

I am certainly not an expert, but I can think of 2 ways:

**Append the language code to the end of the file name**
If I chose to have my captions in Afrikaans and English for example I would have:
`photo.jpg`, `photo.txt_en`, `photo.txt_af`

**Use JSON**
in this case I would have `photo.jpg` and `photo.json`:

```json
{
  "af": "Afrikaans Translation",
  "en": "English Translation"
}
```

**Comment by wavexx** [comment]
Just throwing ideas, another way could be to prefix the line with the locale:

````
en: test
af: test
````

we could stop on double `\n` for parsing the description. Being simple text, it could also be stored in the same structure as part of the txt/xmp data.

But it's definitely uglier.

**Comment by tjaartvdwalt** [comment]
I like your idea best for backwards compatibility.

**Comment by mz64** [comment]
Proposal:
1. allow reading captions from tab-separated text files
    `IMAGE.JPG <tab> My caption`
   * easy to generate from a file listing `ls -1 *.JPG >list.txt`
   * easy to edit
   * provide graceful fallback
   * possibly integrate `fcaption` (tab-separated text file output)
2. support internationalization for caption files `file-name.txt.en`
    * use [language code suffix](https://en.wikipedia.org/wiki/IETF_language_tag)
3. deliver internationalization through server driven [content negotiation](http://httpd.apache.org/docs/2.4/content-negotiation.html)
    * generate internationalized content maps `data.json.en` (some quirks)
    * initially Apache (`mod_negotiation`, `type-map`, `AliasMatch`, a couple of quirks); write simple instructions
    * provide graceful fallback for running locally
    * advantage: zero user interface (keeps with "no frills" vision)
4. Possible future GUI for language switching (not a fan)

[Example](https://s2x.co/x/p/fg/):
* try `fr` or `en` top language option in your browser
* some caching issues when switching languages

@wavexx happy to implement this; let me know.
