### ISSUE TITLE
Support for RAW images

### ISSUE THREAD

**Issue by alespouzar** [wavexx/fgallery#63]
It seems that fgallery can't handle RAW images. It is as easy as to extract an embedded image (preview) from RAW file (e.g. Exiftool is capable of doing this). Would be nice if this functionality could be added to fgallery so one doesn't need to extract JPG previews manually before creating a new gallery.

**Comment by wavexx** [comment]
On Thu, Oct 13 2016, Aleš Pouzar <notifications@github.com> wrote:
> It seems that fgallery can't handle RAW images. It is as easy as to
> extract an embedded image (preview) from RAW file (e.g. Exiftool is
> capable of doing this). Would be nice if this functionality could be
> added to fgallery so one doesn't need to extract JPG previews manually
> before creating a new gallery.

Can you attach a sample DNG with embedded jpeg?

None of my cameras do this.

Technically imagemagick can also read DNG files directly, but it will
develop them using dcraw, which is not what we want as it generally
doesn't match the camera profile.

**Comment by alespouzar** [comment]
I have only CR2 files. Hopefully it helps.
[raw.zip](https://github.com/wavexx/fgallery/files/527862/raw.zip)

**Comment by wavexx** [comment]
I'd love to have a DNG with an embedded jpeg also, but straight from a camera. If anybody can provide one, it would be nice to add to my test set.
