### ISSUE TITLE
do not use link() on VFAT

### ISSUE THREAD

**Issue by elgaard** [wavexx/fgallery#64]
When the source directory is on a filesystem that does not support links (e.g. VFAT) use File:copy() instead of link.

I have images on a 32Gbyte SD-card to be used on a openWRT box with lighttpd. I also use the SD-card in cameras, so it has to be VFAT. I run fgallery on a chromebook with Ubuntu, so there is not enough free space to copy the images to a real FS before running fgallery.

I replaced to link() with File:Copy() in fgallery, and it worked just fine on VFAT, but a bit slower of course.

**Comment by wavexx** [comment]
This should already be the case in fgallery 1.8.2.
Which version did you use?

**Comment by wavexx** [comment]
On Sat, Oct 22 2016, Niels Elgaard Larsen <notifications@github.com> wrote:
> When the source directory is on a filesystem that does not support
> links (e.g. VFAT) use File:copy() instead of link.

This should already be the case in fgallery 1.8.2.
Which version did you use?

**Comment by elgaard** [comment]
Ahh,
1.8.1-1 on Ubunty Xenial.

I checked an Ubunty Yappity box. It hand It had 1.8.2 and i could see it was fixed.
Thank you.

**Comment by wavexx** [comment]
Thennnn.. closing.
