### ISSUE TITLE
Serving from port other than 80 does not work

### ISSUE THREAD

**Issue by bjodah** [wavexx/fgallery#67]
Original config (fgallery did not work):
local server with nginx running on port 80, router NAT exposes that on 20080 to the outside world

Chaning NAT to use port 80 to the outside made things work.

I have not investigated this further (shot in the dark: some javascript snippet forgets to see if there is a port in the url, e.g. `www.myserver.com:20080/~myuser/myfgallery`)

**Comment by wavexx** [comment]
On Mon, Dec 19 2016, Björn Dahlgren wrote:
> Original config (fgallery did not work):
> local server with nginx running on port 80, router NAT exposes that on 20080 to the outside world
>
> Chaning NAT to use port 80 to the outside made things work.
>
> I have not investigated this further (shot in the dark: some
> javascript snippet forgets to see if there is a port in the url, e.g.
> `www.myserver.com:20080/~myuser/myfgallery`)

I suspect there's a redirect involved here (try adding the last slash).
fgallery itself should work.

**Comment by bjodah** [comment]
Thanks, that seems to work. Sorry for the noise.
