### ISSUE TITLE
Support for multi-levels albums

### ISSUE THREAD

**Issue by minibiti** [wavexx/fgallery#70]
Hi,
Would it be a big job to support multi-levels albums (i.e nested directories) in order to be able to sort galleries in sub-galleries?

The idea would be to have something like this:
Top Gallery
-- Gallery1Level1
---- Gallery1Level2
------ Gallery1Level3
---- Gallery1Level2
-- Gallery2Level1
---- Gallery2Level2
---- Gallery2Level2

So one would start and run the fgallery command from the top level and it would generate nested galleries according to the sub-directories tree.
There would be a way to define the main picture and description for each level.

Thanks!

**Comment by paolobenve** [comment]
That would be wonderful!

**Comment by puargs** [comment]
Just a heads up, I made a post-generation utility to handle this: https://github.com/puargs/ftopindexmaker

I know it's not built into the original tool, but it might be helpful to you.

**Comment by paolobenve** [comment]
https://github.com/paolobenve/photofloat implementare It!!!!
