### ISSUE TITLE
Link original image instead of copy

### ISSUE THREAD

**Issue by ecksun** [wavexx/fgallery#72]
I'm hoping to use fgallery for all of my pictures (currently about 100GB), I would also naturally want to include the original image (`-i`), however when fgallery is copying all my original images it takes an unnecessary amount of extra space.

What is done currently is:

    sys('cp', '-L', $file, $fout);

A very simple solution would be to add an option to use hard links instead (`cp --link`) or symlinks (`ln -s`).

**Comment by wavexx** [comment]
Agreed that a flag like ``--link-orig`` would come in handy.
Maybe even taking an argument like ``--link-orig=ref|lhard|sym`` for ``cp --reflink``, ``ln`` and ``ln -s`` respectively.

**Comment by ecksun** [comment]
Yes, that sounds like a good solution.
