### ISSUE TITLE
fgallery crashes if destination directory contain spaces

### ISSUE THREAD

**Issue by paolobenve** [wavexx/fgallery#75]
as per object, a space in destination directory (like "My house") crashes fgallery

**Comment by wavexx** [comment]
On Sun, Apr 02 2017, Paolo wrote:
> as per object, a space in destination directory (like "My house") crashes fgallery

Do you have an example? Which fgallery version are you using?

fgallery should definitely work with spaces in filenames (in both input
and output directories).

**Comment by kensanata** [comment]
Commit ed0b076 in my pull request fixes this.

**Comment by wavexx** [comment]
On Mon, Jun 26 2017, Alex Schroeder wrote:
> Commit ed0b076 in my pull request fixes this.

Thanks for pointing this out, I missed the fact that exiftran wasn't
called in list mode. Using quotes doesn't feel right. It should now work
correctly in all cases.
