### ISSUE TITLE
Make it more social-friendly

### ISSUE THREAD

**Issue by frijsdijk** [wavexx/fgallery#77]
Wonderful piece of software, and looks very good. I'd like to be able to use it together with social sites (mainly Facebook), but linking to a picture (i.e. http://photoblog.isafeelin.org/fgallery/Gallery/#0) won't work for Facebook (no thumbnail or preview loaded in fb-post).

**Comment by wavexx** [comment]
On Sat, May 13 2017, frijsdijk wrote:
> Wonderful piece of software, and looks very good. I'd like to be able
> to use it together with social sites (mainly Facebook), but linking to
> a picture (i.e. http://photoblog.isafeelin.org/fgallery/Gallery/#0)
> won't work for Facebook (no thumbnail or preview loaded in fb-post).

This can probably be improved by tweaking
https://github.com/wavexx/fgallery/pull/60 to include an <a id="#n">
reference for each image as well as an href.

Maybe @kensanata can give it a try?

I never used facebook, but I can guess they're crawling without JS.

**Comment by kensanata** [comment]
Indeed they don't. My patch works well enough for Google+, allowing you to pick a thumbnail picture, but maybe that's no longer good enough these days. For Facebook and Twitter a bit more information is required. If you look at the source code for [this gallery](https://alexschroeder.ch/gallery/2017-zurich/index.html) you'll see that I added the following:

```
    <!-- for Facebook -->
    <meta property="og:title" content="Pictures" />
    <meta property="og:type" content="article" />
    <meta property="og:image" content="https://alexschroeder.ch/gallery/2017-zurich/imgs/IMG_7915.jpg" />
    <meta property="og:url" content="https://alexschroeder.ch/gallery/2017-zurich/" />
    <meta name="twitter:card" content="summary" />
    <!-- for Twitter -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="Pictures" />
    <meta name="twitter:description" content="A gallery of pictures." />
    <meta name="twitter:image" content="https://alexschroeder.ch/gallery/2017-zurich/imgs/IMG_7915.jpg" />
````

Some of this information we would have to supply when generating the gallery:

1. title
2. description
3. URL of the gallery
4. we would have to specify the image to use if we don't want to use the first one

The URL is the tricky part. When I tried providing a relative URL, it didn't work. Thus, the URL of the gallery would have to be provided at the very least, using a command line parameter. We can provide generic defaults for the others.

For future reference, here are two validator sites:

1. [Facebook](https://developers.facebook.com/tools/debug/sharing/) with [documentation](https://developers.facebook.com/docs/sharing/webmasters#markup)
2. [Twitter](https://cards-dev.twitter.com/validator) with [documentation](https://dev.twitter.com/cards/types/summary)

**Comment by kensanata** [comment]
#78 is a stand-alone solution.

**Comment by wavexx** [comment]
On Sat, May 13 2017, Alex Schroeder wrote:
> Indeed they don't. My patch works well enough for Google+, allowing
> you to pick a thumbnail picture, but maybe that's no longer good
> enough these days. For Facebook and Twitter a bit more information is

But did you try to see if they pick up the image correctly if the id=""
is added in the <a> tag itself?

This would make linking to an image with and without JS al least
symmetric, so it's a good idea in any case.

**Comment by frijsdijk** [comment]
Let me know if I can test anything!

**Comment by kensanata** [comment]
@wavexx, I'm not sure why this would help. The documentation for Facebook and Twitter is pretty clear. I changed all the image links as follows, just to verify that it made no difference:
```
<a id="1" href="imgs/P3250004.jpg" title=""><img src="thumbs/P3250004.jpg" alt=""/></a>
```
This is live [for one of my galleries](https://alexschroeder.ch/gallery/2017-zoo/). I then posted a Tweet with a link to that gallery, and typed a Facebook post with a link to that gallery, and as expected I got no preview image.
I do agree that it would be a good idea to allow linking to the image, however.

**Comment by kensanata** [comment]
@frijsdijk, if you want, you can add manually add the meta tags I posted [above](https://github.com/wavexx/fgallery/issues/77#issuecomment-301277114) to your index.html file, replacing the texts and URLs as you see fit, and see whether you get the appropriate effect when you post to Facebook or Twitter.

**Comment by wavexx** [comment]
On Sun, May 14 2017, Alex Schroeder wrote:
> @wavexx, I'm not sure why this would help. The documentation for
> Facebook and Twitter is pretty clear.

If the <a id="x"> uniquely wraps a single image, even a dumb crawler
/should/ be able to locate the image.

Do you know if Google+ also use their own flavor of tags?

**Comment by kensanata** [comment]
Well, Google+ seemed to just take any image I offered. Using the index.html as my branch would generate it, I am offered the big first picture and all the thumbs next for me to pick. It would therefore seem that Google actually crawls the page and takes all the image links – even the image link from the meta data for Facebook and Twitter. In other words, it does what I would have expected to happen without any extra effort on my part. Having a high resolution image available for the preview in Google+ even if it isn't shown on the actual page when you visit is a nice bonus.

The [documentation for developers](https://developers.google.com/+/web/snippet/) suggests that they also use the Open Graph links (Facebook), and they'd like to use schema.org microdata (which I haven't added).

**Comment by wavexx** [comment]
On Sun, May 14 2017, Alex Schroeder wrote:
> The [documentation for
> developers](https://developers.google.com/+/web/snippet/) suggests
> that they also use the Open Graph links (Facebook), and they'd like to
> use schema.org microdata (which I haven't added).

Unless schema.org microdata is actually parsed by Facebook or Twitter
(so that we could use schema.org in favor of a "proprietary" schema),
there's probably no point in supporting an extra format. There's quite
some bloat that's being added in double already.

**Comment by kensanata** [comment]
It would seem to me that schema.org is interesting because it was founded by Google, Microsoft, Yahoo and Yandex, according to their [homepage](http://schema.org/). If somebody other than Facebook and Twitter comes along, what will they rely on? I haven't investigated Microsoft, Yahoo and Yandex and thus I'm in favour of leaving schema.org metadata in there (since I just added it today).

**Comment by frijsdijk** [comment]
@kensanata I've tested the patch actually, and this seems to work. Although it only shows the thumbnail of the first image in the album. So the site/ page works, but site/#1 doesn't (shows the same thumbnail).

So posting http://photoblog.isafeelin.org/fgallery/Family/ to Facebook works.

But http://photoblog.isafeelin.org/fgallery/Family/#{1,2,3} yield the same result. Since the meta data is in the index.html that never changes.. I guess this is a bit of a problem, no?

**Comment by kensanata** [comment]
This is correct and I don't know a way around that. No matter which image you link, the index file is always used and thus the preview image will always be the same. Only a major change with multiple HTML files would fix that.
