### ISSUE TITLE
more robust against bad input

### ISSUE THREAD

**Issue by monopole** [wavexx/fgallery#81]
I've got hundreds of thousands of files recovered from a disk recovery tool, and it appears that if any one of the purported image files (.jpg, .tiff, .gif etc) in a directory experiences an error like

```
[tificc fatal error]: Input profile is not operating in proper color space
error: command "tificc -t0 /mnt/sortedRecovery/png_above_01.0M_below_02.0M_GALLERY/files/f2378666288.png.tmp /mnt/sortedRecovery/png_above_01.0M_below_02.0M_GALLERY/files/f23786
```

then the directory scan appears to fail, and the `data.json` file is not created.

Without that file, the js crashes in browser when requesting it, because the file is not there to be served, so its not possible to browse _any_ photos.  I'd rather see error logging, and partial success.

Either that or I'm holding it wrong :)

Can you suggest a workaround?  Is there a flag to suppress the use of `tificc`?

**Comment by wavexx** [comment]
On Mon, Jun 19 2017, Jeff Regan wrote:
> ```
> [tificc fatal error]: Input profile is not operating in proper color space
> error: command "tificc -t0 /mnt/sortedRecovery/png_above_01.0M_below_02.0M_GALLERY/files/f2378666288.png.tmp /mnt/sortedRecovery/png_above_01.0M_below_02.0M_GALLERY/files/f23786
> ```

Could you send over a sample image? (even privately if you wish).

> Can you suggest a workaround?  Is there a flag to suppress the use of `tificc`?

Are you using the git version or the last released version?

The colorspace conversion can be skipped with "--no-sRGB" on the command
line.
