### ISSUE TITLE
[INFO] FreeBSD port for fgallery and facedetect created

### ISSUE THREAD

**Issue by ehaupt** [wavexx/fgallery#82]
Just wanted to let you know that I find fgallery very useful and therefore created an official FreeBSD port for both fgallery and facedetect:

http://www.freshports.org/www/fgallery/
http://www.freshports.org/graphics/facedetect/

The packages on FreeBSD can be installed like so:

facedetect:
```
$ pkg install facedetect
```

fgallery (will install facedetect as a dependency):
```
$ pkg install fgallery
```

**Comment by wavexx** [comment]
Thanks a lot. I added the instructions.
