### ISSUE TITLE
Slideshow mode

### ISSUE THREAD

**Issue by mz64** [wavexx/fgallery#88]
Proposal: add slideshow mode
1. `play` button in main mode starts slideshow mode
    * button position TBD
    * image goes to full screen with padding (black or blurs; TBD)
2. `delay` (seconds) is configurable in slideshow mode
    * up/down arrows 
3. `pause` button (slideshow mode; hover) keeps the current picture on indefinitely
    * left/right arrows move between full screen pictures (TBD)
    * `play` button (on hover)
4. `autoplay` when idle in main mode
    * `autoplay` on/off similar with youtube (position right top? TBD)
    * delay can be configured through `fgallery` command line

@wavexx: I am happy to implement this; let me know

should be merged with #4

**Comment by usonianhorizon** [comment]
Hello.

I too would love to see this.  I have just begun to use fgallery after many years of using shalbum, and find it a pleasure to work with.  Have a slideshow mode as outlined by the OP would round out the feature set nicely.

Thanks.

**Comment by kensanata** [comment]
[Sitelen Mute](https://github.com/kensanata/sitelen-mute) is a fork of fgallery. If you click away the thumbs, the slide show starts. Example gallery: https://alexschroeder.ch/gallery/2018-scotland/

**Comment by usonianhorizon** [comment]
Thanks for this! That's just what I was looking for.
