### ISSUE TITLE
Tree of albums with overview pages?

### ISSUE THREAD

**Issue by hartwork** [wavexx/fgallery#92]
Hi!

Is there a way to have a directory structure like ..

* Exhibitions
  * Year 1
    * Month 1 City 1
      * _image files_
    * Month 2 City 2
      * _image files_

.. result in a tree of albums with overview pages, [a bit like lazygal](https://photos.cihar.com/gallery/index.html) would do (but maybe less playful)? Are there plans to add a feature like that?

Thanks and best, Sebastian

**Comment by wavexx** [comment]
There was a plan, but I'm not gonna lie: it unlikely to be finished soon. See #70.

I started some work in the "album" tree with the plan to read directly the json files produced by each individual files and create the album view on the fly by picking a random set of images and using them as thumbnails in a thin strip, pretty much the thumbnails already visible in the gallery.

Pretty much like the rest of the interface, I generally keep frills to a minimum. Here the dynamic preview  allows one to see the content of the album. I hate having to go into a folder just to see two sample images and go back. This is where most of the sub-folder-style galleries fail. "Random browsing" should be smooth.

I didn't do much work lately on fgallery. Aside from other projects, my main camera started to have some issues last year, and I didn't have the budget to replace it with something I'd like, causing me to take way less photos as a result.

**Comment by hartwork** [comment]
Thanks for your quick reply and sharing details. With open #70 I'm okay with closing this one here as a duplicate if you like.
