### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by tyeeman** [wavexx/fgallery#93]
Can this be installed or made to work in Windows 7?

**Comment by wavexx** [comment]
On Sat, Aug 11 2018, tyeeman wrote:
> Can this be installed or made to work in Windows 7?

Likely using activeperl since I've used exiftool using it in the past.
Also probably (and maybe easily) using cygwin.

However I stopped using windows regularly more than 10+ years ago, so I
cannot help you going here.
